name: Release CI
on:
  push:
    branches:
      - main
      - next
      - rc
permissions:
      contents: read
      pages: write
      id-token: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install deps
        run: bun i

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build

      - name: Release
        run: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}